### ISSUE TITLE
Current version is not working.

### ISSUE THREAD

**Issue by Alan1321** [DHI-GRAS/terracotta#305] opened 2023-05-03 06:46 UTC
I have successfully used terracotta in the past but when I tried it again today, it did not work. 
I use wsl.
I cloned the latest version 0.8.0 and then used conda for installation. 
I tried the steps given in the Readme.md file.
Everything worked until Step 4 command: terracotta connect localhost:5000 which gave me errors:
"to load resource: the server responded with a status of 404 (NOT FOUND)"

**Comment by j08lue** [comment] 2023-05-03 08:11
Can you post the terminal output of your `terracotta serve` command, please?

**Comment by Alan1321** [comment] 2023-05-03 13:10
@j08lue 
Here are all the errors.

######Terminal Output of terracotta serve:

 * Running on http://localhost:5000
Press CTRL+C to quit
127.0.0.1 - - [03/May/2023 08:06:19] "GET /keys HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:19] "GET /swagger.json HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:24] "GET /keys HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:24] "GET /datasets?limit=15&page=0 HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:24] "GET /metadata/B02/20160724/27XVB HTTP/1.1" 404 -
127.0.0.1 - - [03/May/2023 08:06:35] "GET /keys HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:35] "GET /datasets?limit=15&page=0 HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:36] "GET /metadata/B02/20160724/27XVB HTTP/1.1" 404 -

######Terminal Output of terracotta connect localhost:5100

 * Running on http://127.0.0.1:5100
Press CTRL+C to quit
127.0.0.1 - - [03/May/2023 08:06:23] "GET / HTTP/1.1" 200 -
127.0.0.1 - - [03/May/2023 08:06:23] "GET /static/react/static/js/2.83c1f4db.chunk.js HTTP/1.1" 304 -
127.0.0.1 - - [03/May/2023 08:06:23] "GET /static/react/static/css/2.19072978.chunk.css HTTP/1.1" 304 -
127.0.0.1 - - [03/May/2023 08:06:23] "GET /static/react/static/js/main.edc7f98e.chunk.js HTTP/1.1" 304 -
127.0.0.1 - - [03/May/2023 08:06:23] "GET /static/react/static/media/header.87193822.svg HTTP/1.1" 304 -
127.0.0.1 - - [03/May/2023 08:06:24] "GET /static/react/manifest.json HTTP/1.1" 304 -
127.0.0.1 - - [03/May/2023 08:06:24] "GET /static/react/logo192.png HTTP/1.1" 304 -
127.0.0.1 - - [03/May/2023 08:06:34] "GET / HTTP/1.1" 200 -

######Errors shown on the frontend console

Failed to load resource: the server responded with a status of 404 (NOT FOUND)
React-dom.production.min.js:216 TypeError: Cannot convert undefined or null to object
    at Function.keys (<anonymous>)
    at ie (TableRow.tsx:70:28)
    at ia (react-dom.production.min.js:157:137)
    at Zs (react-dom.production.min.js:267:460)
    at Cl (react-dom.production.min.js:250:347)
    at Tl (react-dom.production.min.js:250:278)
    at Sl (react-dom.production.min.js:250:138)
    at gl (react-dom.production.min.js:243:163)
    at react-dom.production.min.js:123:115
    at t.unstable_runWithPriority (scheduler.production.min.js:18:343)
s

**Comment by dionhaefner** [comment] 2023-05-05 09:35
Works on my machine™️

I see that `/metadata` throws a 404, so the client requests metadata for a non-existing image (as returned by `/datasets`). It looks to me like your database may be corrupted.

To debug this properly I think we would need the exact commands you ran.

**Comment by dionhaefner** [comment] 2023-09-26 12:32
Duplicate of #314.

**Closed by dionhaefner** 2023-09-26 12:32 UTC
Labels: bug
