### ISSUE TITLE
No RGB available for selection

### ISSUE THREAD

**Issue by JackMismash** [DHI-GRAS/terracotta#310] opened 2023-08-08 17:13 UTC
When in the terracotta preview app, I try to select rgb. There are no bands available for selection from the drop down when i switch to rgb. Nothing loads either. Any suggestions?

For reference, this is when i click to change the R band. Nothing shows up: 
![image](https://github.com/DHI-GRAS/terracotta/assets/110419587/68449f16-25b7-44d2-ba8a-8e6407fe3706)

**Comment by dionhaefner** [comment] 2023-08-09 08:53
That's strange. Does singleband work? Do you see any errors in the javascript console?

**Comment by JackMismash** [comment] 2023-08-09 15:35
Singleband does work, and grayscale tiles do appear and I can zoom in and watch the tiles load. If it helps, I have .tif images from the USGS Earth Explorer. When I run terracotta optimize-rasters on these tif files the logging says there are multiple bands in the image so it only selects one which I believe is the desired behavior, since there are multiple bands in the image. I am trying to use gdal to split the file into multiple bands. e.g. if my file name is 'file.tif' I split it into 4 different files using gdal to get each band -> 

file_1.tif
file_2.tif
file_3.tif
file_4.tif

When I use terracotta optimize-rasters on these files, since there is only one band in each file, the log doesn't show anything about selecting only one band. After I put these files into the sqlite database and serve it up. However, no tiles appear at all and the web application is completely blank. The logging shows that my GET request for keys, swagger.json, datasets, and keys works (those all happen in that respective order). However, the GET request for metadata fails:

**Comment by dionhaefner** [comment] 2023-08-09 22:28
Thanks, that's helpful. It sounds like you did everything correctly.

A 404 error indicates that no dataset has been found with the given keys. I'm also confused by `GET /metadata/B1/file`, shouldn't it be `GET /metadata/file/B1` given that the pattern is `{name}_{band}.tif`?

Can you run the server from the command line, then point your browser to `localhost:5000/keys` and `localhost:5000/datasets` and post the output here?

**Comment by JackMismash** [comment] 2023-08-09 22:32
It seems like a previewer issue, I ran it from postman and was able to receive rgb images. I pointed it to cesium.js and I am able to receive and zoom into rgb tiles. However, when trying to run 'terracotta connect localhost:5000', the previewer doesn't show anything. I am not sure what could be the issue, but I think the server is working, just not the previewer web app.

**Comment by dionhaefner** [comment] 2023-08-10 11:02
Yes it seems like something is wrong with the metadata requests, which isn't used by cesium.

Could do what I suggested above? I.e.,

1. Start the server with `terracotta serve`.
2. Go to `localhost:5000/keys` and `localhost:5000/datasets` in a browser window or use `curl`, then post the results here (not using the web app).

**Comment by dionhaefner** [comment] 2023-09-26 12:32
Duplicate of #314.

**Closed by dionhaefner** 2023-09-26 12:32 UTC
Labels: bug
